name: ci-redis

on: push

jobs:
  test:
    strategy:
      matrix:
        stack: [heroku-22, heroku-24]
        redis_version: ["", "7", "8"]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Run Test
      run: ./bin/test.sh ${{ matrix.stack }}
      env:
        REDIS_VERSION: ${{ matrix.redis_version }}

  # dummy job to wait and block merge until all jobs have completed
  done:
    runs-on: ubuntu-latest

    needs: [test]

    steps:
      - run: echo done
        working-directory: /
