name: ci-redis

on: push

jobs:
  test:
    strategy:
      matrix:
        stack: [heroku-22, heroku-24, heroku-26]
        valkey_version: ["", "7.2", "8", "8.1", "9", "9.1", "7.2.13"]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Run Test
      run: ./bin/test.sh ${{ matrix.stack }}
      env:
        VALKEY_VERSION: ${{ matrix.valkey_version }}

  # dummy job to wait and block merge until all jobs have completed
  done:
    runs-on: ubuntu-latest

    needs: [test]

    steps:
      - run: echo done
        working-directory: /
